#!/usr/bin/env bash
# Creates a DEVELOPMENT setup for jarvisd under daemons/mac-daemon/.dev/:
#
#   .dev/config/daemon.toml       config (loopback mode; workspace = this repo)
#   .dev/config/tls/              throwaway CA + server certificate
#   .dev/orchestrator/            client certificate for grpcurl (the "orchestrator")
#   .dev/approver/                approver key for jarvis-approve (the "phone")
#
# The whole .dev directory is a protected path: sandboxed commands can neither
# read the keys nor rewrite the configuration.
#
# Usage: scripts/dev-setup.sh [--force]
set -euo pipefail

cd "$(dirname "$0")/.."
DAEMON_DIR=$(pwd)
REPO_ROOT=$(cd ../.. && pwd)
DEV="$DAEMON_DIR/.dev"
TRUST_DOMAIN="jarvis.local"
DAYS=30

if [[ -f $DEV/config/daemon.toml && ${1:-} != --force ]]; then
  echo "Development setup already exists in $DEV (use --force to recreate)."
  exit 0
fi
rm -rf "$DEV"
umask 077
mkdir -p "$DEV/config/tls" "$DEV/orchestrator" "$DEV/approver"

# --- certificates -----------------------------------------------------------
new_key() { openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:P-256 -out "$1" 2>/dev/null; }
TLS="$DEV/config/tls"
new_key "$TLS/ca-key.pem"
openssl req -x509 -new -key "$TLS/ca-key.pem" -out "$TLS/ca.pem" -days "$DAYS" \
  -subj "/CN=Jarvis Daemon Development CA" \
  -addext "basicConstraints=critical,CA:TRUE" -addext "keyUsage=critical,keyCertSign,cRLSign"

issue() { # issue <key> <cert> <cn> <eku> <san>
  new_key "$1"
  openssl req -new -key "$1" -out "$2.csr" -subj "/CN=$3"
  openssl x509 -req -in "$2.csr" -CA "$TLS/ca.pem" -CAkey "$TLS/ca-key.pem" -CAcreateserial \
    -out "$2" -days "$DAYS" 2>/dev/null \
    -extfile <(printf 'basicConstraints=critical,CA:FALSE\nkeyUsage=critical,digitalSignature\nextendedKeyUsage=%s\nsubjectAltName=%s\n' "$4" "$5")
  rm -f "$2.csr"
}

server_san="DNS:localhost,IP:127.0.0.1"
# `tailscale ip` knows this node's address even while Tailscale is stopped.
tailscale_ip=$(tailscale ip -4 2>/dev/null | head -n1 || true)
if [[ -n $tailscale_ip ]]; then
  server_san+=",IP:$tailscale_ip"
  echo "The server certificate also covers this Mac's Tailscale address $tailscale_ip."
fi
issue "$TLS/server-key.pem" "$TLS/server.pem" jarvisd serverAuth "$server_san"
issue "$DEV/orchestrator/client-key.pem" "$DEV/orchestrator/client.pem" orchestrator clientAuth \
  "URI:spiffe://$TRUST_DOMAIN/orchestrator"
cp "$TLS/ca.pem" "$DEV/orchestrator/ca.pem"
rm -f "$TLS/ca.srl" "$TLS/ca-key.pem" # the dev CA signs nothing else
chmod 644 "$TLS/server.pem" "$TLS/ca.pem"

# --- approver key -------------------------------------------------------------
cargo build --quiet -p jarvis-daemon
approver_entry=$("$REPO_ROOT/target/debug/jarvis-approve" --key "$DEV/approver/approver-key.pem" keygen --id dev-cli 2>/dev/null)

# --- configuration ----------------------------------------------------------------
device_name=$(scutil --get ComputerName 2>/dev/null || hostname -s)
cat > "$DEV/config/daemon.toml" <<EOF
# jarvisd DEVELOPMENT configuration, generated by scripts/dev-setup.sh.
device_name = "$device_name"

[network]
# "loopback" serves 127.0.0.1 only. Switch to "tailscale" (and re-run
# dev-setup.sh while Tailscale is up) to serve this Mac's tailnet address.
mode = "loopback"
port = 7443
reflection = true

[tls]
cert = "$TLS/server.pem"
key = "$TLS/server-key.pem"
client_ca = "$TLS/ca.pem"

# Who may call the daemon (URI SAN of the client certificate).
[[principal]]
id = "spiffe://$TRUST_DOMAIN/orchestrator"
allow = ["GetCapabilities", "ExecuteCommand"]

# Who may approve commands outside the allowlist.
$approver_entry

[sandbox]
workspace_roots = ["$REPO_ROOT"]
protected_paths = ["$DEV"]

# Allowlist: these run without asking. Everything else needs approval.
[[command]]
program = "/usr/bin/git"
args_prefix = ["status"]
allow_extra_args = true
description = "Show the working tree status"

[[command]]
program = "/usr/bin/git"
args_prefix = ["log"]
allow_extra_args = true
description = "Show commit history"

[[command]]
program = "/usr/bin/git"
args_prefix = ["diff"]
allow_extra_args = true
description = "Show changes"

[[command]]
program = "/bin/ls"
allow_extra_args = true
description = "List files"

[[command]]
program = "/bin/pwd"
description = "Print the working directory"
EOF

"$REPO_ROOT/target/debug/jarvisd" --config "$DEV/config/daemon.toml" check
echo
echo "Next: scripts/dev-run.sh, then scripts/grpc.sh in another terminal."
